-- Complete Database Setup Script
-- Run this single script in Supabase SQL Editor to set up everything at once

-- =================================================================
-- STEP 1: CREATE TYPES AND TABLES
-- =================================================================

-- Create custom types
CREATE TYPE "public"."Role" AS ENUM ('customer', 'admin');

-- Create locations table
CREATE TABLE IF NOT EXISTS "public"."locations" (
    "location_id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "area" text NOT NULL,
    "city" text NOT NULL,
    "state" text NOT NULL,
    "pincode" text NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "updated_at" timestamp with time zone DEFAULT now(),
    PRIMARY KEY ("location_id")
);

-- Create venues table
CREATE TABLE IF NOT EXISTS "public"."venues" (
    "venue_id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "venue_name" text NOT NULL,
    "location_id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "updated_at" timestamp with time zone DEFAULT now(),
    PRIMARY KEY ("venue_id"),
    FOREIGN KEY ("location_id") REFERENCES "public"."locations"("location_id")
);

-- Create events table
CREATE TABLE IF NOT EXISTS "public"."events" (
    "event_id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" text NOT NULL,
    "description" text,
    "start_time" timestamp with time zone NOT NULL,
    "end_time" timestamp with time zone NOT NULL,
    "image_url" text,
    "image_path" text,
    "created_at" timestamp with time zone DEFAULT now(),
    "updated_at" timestamp with time zone DEFAULT now(),
    PRIMARY KEY ("event_id")
);

-- Create events_venues junction table
CREATE TABLE IF NOT EXISTS "public"."events_venues" (
    "event_venue_id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "event_id" bigint NOT NULL,
    "venue_id" bigint NOT NULL,
    "event_date" date NOT NULL,
    "no_of_tickets" integer NOT NULL DEFAULT 0,
    "price" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "updated_at" timestamp with time zone DEFAULT now(),
    PRIMARY KEY ("event_venue_id"),
    FOREIGN KEY ("event_id") REFERENCES "public"."events"("event_id"),
    FOREIGN KEY ("venue_id") REFERENCES "public"."venues"("venue_id")
);

-- Create users table
CREATE TABLE IF NOT EXISTS "public"."users" (
    "user_id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "supabase_id" uuid UNIQUE,
    "name" text,
    "email" text,
    "address1" text,
    "address2" text,
    "address3" text,
    "location_id" bigint,
    "role" "public"."Role" DEFAULT 'customer',
    "created_at" timestamp with time zone DEFAULT now(),
    "updated_at" timestamp with time zone DEFAULT now(),
    PRIMARY KEY ("user_id"),
    FOREIGN KEY ("location_id") REFERENCES "public"."locations"("location_id")
);

-- Create tickets table with correct column name
CREATE TABLE IF NOT EXISTS "public"."tickets" (
    "ticket_id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "customer_id" integer NOT NULL,
    "event_venue_id" bigint NOT NULL,
    "ticket_price" bigint NOT NULL,
    "quantity" integer NOT NULL DEFAULT 1,
    "created_at" timestamp with time zone DEFAULT now(),
    "updated_at" timestamp with time zone DEFAULT now(),
    PRIMARY KEY ("ticket_id"),
    FOREIGN KEY ("customer_id") REFERENCES "public"."users"("user_id"),
    FOREIGN KEY ("event_venue_id") REFERENCES "public"."events_venues"("event_venue_id")
);

-- =================================================================
-- STEP 2: ENABLE ROW LEVEL SECURITY
-- =================================================================

ALTER TABLE "public"."events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."venues" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."locations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."events_venues" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."tickets" ENABLE ROW LEVEL SECURITY;

-- =================================================================
-- STEP 3: CREATE ALL RLS POLICIES
-- =================================================================

-- Public read policies for events, venues, locations, events_venues
CREATE POLICY "Allow public read access to events" ON "public"."events" FOR SELECT USING (true);
CREATE POLICY "Allow public read access to venues" ON "public"."venues" FOR SELECT USING (true);
CREATE POLICY "Allow public read access to locations" ON "public"."locations" FOR SELECT USING (true);
CREATE POLICY "Allow public read access to events_venues" ON "public"."events_venues" FOR SELECT USING (true);

-- Policies for users table
CREATE POLICY "Allow service role to manage users" ON "public"."users"
  FOR ALL USING (true);

CREATE POLICY "Users can read own profile" ON "public"."users" 
  FOR SELECT USING (auth.uid() = supabase_id);

CREATE POLICY "Users can update own profile" ON "public"."users" 
  FOR UPDATE USING (auth.uid() = supabase_id);

-- Policies for tickets table  
CREATE POLICY "Users can read own tickets" ON "public"."tickets"
  FOR SELECT USING (
    customer_id IN (
      SELECT user_id FROM public.users WHERE supabase_id = auth.uid()
    )
  );

CREATE POLICY "Users can create tickets" ON "public"."tickets"
  FOR INSERT WITH CHECK (
    customer_id IN (
      SELECT user_id FROM public.users WHERE supabase_id = auth.uid()
    )
  );

-- Allow service role full access to tickets (for RPC functions)
CREATE POLICY "Service role can manage tickets" ON "public"."tickets"
  FOR ALL USING (true);

-- =================================================================
-- STEP 4: GRANT PERMISSIONS
-- =================================================================

GRANT USAGE ON SCHEMA public TO service_role;
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO service_role;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO service_role;

-- =================================================================
-- STEP 5: CREATE FUNCTIONS
-- =================================================================

-- User profile creation trigger function
CREATE OR REPLACE FUNCTION "public"."create_user_profile"()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.users (supabase_id, name, email)
  VALUES (
    NEW.id,
    NEW.raw_user_meta_data->>'full_name',
    NEW.email
  );
  RETURN NEW;
END;
$$;

-- Book ticket function with correct column name
CREATE OR REPLACE FUNCTION public.book_ticket(
  p_event_venue_id bigint,
  p_quantity int DEFAULT 1
) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
AS $$
DECLARE
  v_auth_uuid UUID;
  v_internal_user_id INT;
  v_venue_details RECORD;
BEGIN
  -- Validate quantity
  IF p_quantity < 1 THEN
    RAISE EXCEPTION 'Quantity must be at least 1';
  END IF;

  -- Get the current user's auth UUID from the session
  SELECT auth.uid() INTO v_auth_uuid;
  IF v_auth_uuid IS NULL THEN
    RAISE EXCEPTION 'User is not authenticated.';
  END IF;

  -- Get the internal user_id
  SELECT user_id INTO v_internal_user_id
  FROM public.users
  WHERE supabase_id = v_auth_uuid
  LIMIT 1;

  -- Verify a user profile was found
  IF v_internal_user_id IS NULL THEN
    RAISE EXCEPTION 'User profile not found. Please complete your profile before booking.';
  END IF;

  -- Check for ticket availability and lock the row
  SELECT * INTO v_venue_details
  FROM public.events_venues
  WHERE event_venue_id = p_event_venue_id FOR UPDATE;

  IF v_venue_details.event_venue_id IS NULL THEN
      RAISE EXCEPTION 'Event venue not found.';
  END IF;

  IF v_venue_details.no_of_tickets < p_quantity THEN
    RAISE EXCEPTION 'Not enough tickets available. Only % tickets remaining.', v_venue_details.no_of_tickets;
  END IF;

  -- Decrement the ticket count
  UPDATE public.events_venues
  SET no_of_tickets = no_of_tickets - p_quantity
  WHERE event_venue_id = p_event_venue_id;

  -- Create the ticket record
  INSERT INTO public.tickets(customer_id, event_venue_id, ticket_price, quantity)
  VALUES (v_internal_user_id, p_event_venue_id, v_venue_details.price, p_quantity);

END;
$$;

-- Get my bookings function
CREATE OR REPLACE FUNCTION "public"."get_my_bookings"()
RETURNS SETOF "public"."tickets"
LANGUAGE sql SECURITY DEFINER
AS $$
  SELECT *
  FROM public.tickets
  WHERE customer_id IN (
    SELECT user_id FROM public.users WHERE supabase_id = auth.uid()
  );
$$;

-- =================================================================
-- STEP 6: CREATE TRIGGER
-- =================================================================

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.create_user_profile();

-- =================================================================
-- STEP 7: INSERT SAMPLE DATA
-- =================================================================

-- Insert locations
INSERT INTO public.locations (area, city, state, pincode) VALUES
('Marine Drive', 'Mumbai', 'Maharashtra', '400020'),
('Connaught Place', 'Delhi', 'Delhi', '110001'),
('Brigade Road', 'Bangalore', 'Karnataka', '560025');

-- Insert venues
INSERT INTO public.venues (venue_name, location_id) VALUES
('Capital Concert Hall', 1),
('Marine Drive Auditorium', 2),
('Garden City Arena', 3);

-- Insert events
INSERT INTO public.events (name, description, start_time, end_time, image_url) VALUES
('Summer Music Fest 2025', 'A spectacular summer music festival featuring top artists', '2025-07-15 18:00:00+00', '2025-07-15 23:00:00+00', 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea'),
('Tech Conference 2025', 'Annual technology conference with industry leaders', '2025-08-20 09:00:00+00', '2025-08-20 17:00:00+00', 'https://images.unsplash.com/photo-1540575467063-178a50c2df87'),
('The Grand Comedy Show', 'Evening of comedy with renowned comedians', '2025-09-05 19:00:00+00', '2025-09-05 22:00:00+00', 'https://images.unsplash.com/photo-1602673221252-6868b6d51a2e');

-- Insert events_venues (event-venue combinations)
INSERT INTO public.events_venues (event_id, venue_id, event_date, no_of_tickets, price) VALUES
(1, 3, '2025-07-15', 87, 250000),    -- Summer Music Fest at Garden City Arena
(2, 2, '2025-08-20', 241, 500000),   -- Tech Conference at Marine Drive Auditorium  
(3, 1, '2025-09-05', 47, 120000);    -- Comedy Show at Capital Concert Hall

-- =================================================================
-- SETUP COMPLETE! 🚀
-- ================================================================= 